[package]
name = "analytics"
version = "0.1.0"
edition = "2021"

# Specify instructions on how to build the library
[lib]
name = "analytics"
crate-type = ["cdylib"] # dynamic system library with a C-compatible Foreign Function Interface

[dependencies]
serde = { version = "1", features = ["derive"] }
bytes = { version = "1.10"}
bitvec = { version = "1.0.1", features = ["serde"] }

#Polars and pyo3
polars = { version = "0.51.0", features = ["lazy", "performant"] }
polars-arrow = { version = "0.51.0", default-features = false }
pyo3 = { version = "0.25.0", features = ["extension-module", "abi3-py39"] }
pyo3-polars = { version = "0.24.0", features = ["derive", "dtype-struct", "dtype-array", "dtype-categorical", "lazy"] }

#Concurrent hashmaps & hashing functions
scc = "2"
murmur3 = "0.5"
wyhash = "0.5"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
ahash = "0.8"       # Fast non-cryptographic hashing for MinHash
rustc-hash = "2.1"
foldhash = "0.1"

#Parallelism
rayon = "1.10"

#SIMD
wide = "0.7"        # Portable SIMD operations
mimalloc = "0.1.48"

#Random
rand = "0.8"
rand_xoshiro = "0.6"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[features]
default = ["python"]
python = []

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3

[profile.bench]
lto = "thin"
codegen-units = 1